version: "2"

services:
  # Flask 后端服务
  app:
    image: python:3.9
    container_name: flask_app
    privileged: true
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://root:zxyoright@db:5432/zxy
    volumes:
      - ./backend:/usr/src/app
      - ./postgres/init:/docker-entrypoint-initdb.d
    working_dir: /usr/src/app
    #command: sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    depends_on:
      - db

  # PostgreSQL 数据库服务
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    privileged: true
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: zxyoright
      POSTGRES_DB: zxy
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  # Vue 前端服务
  frontend:
    image: node:16
    container_name: vue_frontend
    privileged: true
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "npm install && npm run serve"
    ports:
      - "8080:8080"

volumes:
  pgdata:
    driver: local
